#!/bin/sh

# Run Gitleaks to scan the repository for secrets
echo "Running Gitleaks pre-push hook..."

gitleaks detect --source . --config .gitleaks.toml --verbose

# Check the exit code of Gitleaks
if [ $? -ne 0 ]; then
  echo "Secrets were detected by Gitleaks! Push aborted."
  exit 1  # Abort the push
else
  echo "No secrets detected by Gitleaks. Proceeding with push."
fi

